apiVersion: v1
kind: Service
metadata:
  name: yelplabel-frontend
  labels:
    app: yelplabel
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: "http-server"
  selector:
    app: yelplabel
    role: frontend

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: yelplabel-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yelplabel
        role: frontend
    spec:
      containers:
      - name: yelplabel-frontend
        image: gcr.io/$GCLOUD_PROJECT/yelplabel-frontend
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis-master
        - name: GCLOUD_PROJECT
          value: $GCLOUD_PROJECT
        ports:
        - name: http-server
          containerPort: 8080
