---
swagger: "2.0"
info:
  description: "A simple service to get list of images in OpenStack glance"
  version: "0.0.1"
  title: "OpenStack_Glance"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Openstack_imageservice example"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /list_images:
    get:
      summary: "Get list of images stored in glance"
      description: " "
      operationId: "list_images_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "images list"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/list_images"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  list_images:
    type: "object"
    required:
    - "model"
    properties:
      model:
        type: "string"
    example:
      model: "model"
